
favicon:     "images/favicon.ico"
title: Seek Addo
description: "Secure internet for all."
url: "https://www.seekaddo.me"
author: "Dennis Addo"
keywords: "vulhub,secure coding,kali linux,code,startups,technology,tech"
github: seekaddo
twitter:
email: dennis_addo@aol.com


### Personal info and site tools info:
twitter_username: yulijia
github_username:  yulijia
disqus_shortname: freshman21
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Lijia Yu. I made the Freshman21 theme. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg# your photo.
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)



exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]

permalink: pretty
timezone: Europe/Vienna

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
      
      
      
image_path: images
