
favicon:     "images/favicon.ico"
title: Seek Addo
description: "Secure internet for all."
url: "https://www.seekaddo.me"
author: "Dennis Addo"
keywords: "vulhub,secure coding,kali linux,code,startups,technology,tech"
github: seekaddo
twitter:
email: dennis_addo@aol.com

aboutme: Hey there! I'm Dennis Addo (Seek Addo). I am a Ghanaian living in Vienna, Austria.

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]

permalink: pretty
timezone: Europe/Vienna

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
      
      
      
image_path: images
